"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {createSupabaseServerClient} from "@/lib/supabase/server";
const ADMIN=process.env.ADMIN_EMAIL||"marcneizha@gmail.com";
async function db(){const s=await createSupabaseServerClient();const{data:{user}}=await s.auth.getUser();if(!user||user.email?.toLowerCase()!==ADMIN.toLowerCase())throw new Error("Not authorized");return s}
export async function addContestant(f:FormData){const s=await db();const start=Number(f.get("starting_balance"));const current=Number(f.get("current_balance"));const{error}=await s.from("contestants").insert({name:String(f.get("name")),broker:String(f.get("broker")),starting_balance:start,current_balance:current,status:String(f.get("status"))});if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/admin")}
export async function updateContestant(f:FormData){const s=await db();const id=String(f.get("id"));const balance=Number(f.get("current_balance"));const{error}=await s.from("contestants").update({current_balance:balance,status:String(f.get("status"))}).eq("id",id);if(error)throw new Error(error.message);await s.from("balance_history").insert({contestant_id:id,balance,recorded_on:new Date().toISOString().slice(0,10)});revalidatePath("/");revalidatePath("/admin")}
export async function removeContestant(f:FormData){const s=await db();const{error}=await s.from("contestants").delete().eq("id",String(f.get("id")));if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/admin")}
export async function saveChallenge(f:FormData){const s=await db();await s.from("challenges").update({active:false}).eq("active",true);const{error}=await s.from("challenges").insert({name:String(f.get("name")),start_date:String(f.get("start_date")),end_date:String(f.get("end_date")),starting_balance:Number(f.get("starting_balance")),active:true});if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/admin")}
export async function addContent(f:FormData){const s=await db();const{error}=await s.from("content_items").insert({type:String(f.get("type")),title:String(f.get("title")),description:String(f.get("description"))});if(error)throw new Error(error.message);revalidatePath("/updates");revalidatePath("/admin")}
export async function signOut(){const s=await createSupabaseServerClient();await s.auth.signOut();redirect("/")}
